 GET http://localhost:3000/data/all_data/672fbc16eec181dde7748cbd
 Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1JbGlAZ21haWwuY29tIiwiaWF0IjoxNzMxMTkwNTEwfQ.Xz8H8dBj6uR5zX2CS5Vz-vFFk-0NCyT89aRIHuKKxsk",
}

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ik1JbGlAZ21haWwuY29tIiwiaWF0IjoxNzMxMTkwNTEwfQ.Xz8H8dBj6uR5zX2CS5Vz-vFFk-0NCyT89aRIHuKKxsk",
}


POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "MIli@gmail.com",
    "password": "MILI"
}

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstName":"MIlli",
    "lastName":"Aleisx",
    "email":"MIli@gmail.com",
    "password":"MILI",
    "profileImage":"1233edsd3e2efg322egdg",
    "description":"BIg Smoke ",
    "socialLinks": [
    {
      "platform": "LinkedIn",
      "url": "http://links_social:23/sd"
    }
  ]
}
